import type { Metadata } from "next";
import Header from "../app/layout/header";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin", "cyrillic"],
  weight: "500", // 500 соответствует Medium
});

export const metadata: Metadata = {
  title: "Isk master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="dark" lang="en" className={jetBrainsMono.className}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
