// ./src/app/layout.tsx
import type { Metadata } from 'next';
import Header from '@/src/components-feature/header';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';

const jetBrainsMono = JetBrains_Mono({
    subsets: ['latin', 'cyrillic'],
    weight: ['300', '400'], // Подключаем тонкий (300) и стандартный (400) веса
    variable: '--font-jetbrains-mono', // Регистрируем CSS-переменную для globals.css
});

export const metadata: Metadata = {
    title: 'Isk master',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html data-theme="dark" lang="en" className={jetBrainsMono.className}>
            <body>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
